### ISSUE TITLE
USER STORY: Edit/Delete Reviews

### ISSUE THREAD

**Issue by Hugh1996** [Hugh1996/sabor-asturiano-pp4#16]
As a **User** I can **edit or delete my reviews** so that **I can manage them**

## Acceptance Criteria
* Users can edit and delete their own reviews.
* Edited reviews reflect the updated content.
* Deleted reviews are not visible to other regular users.

## Tasks
- [x] Enable users to edit and update their own reviews.
- [x] Enable users to delete their own reviews.
- [x] Implement a user-friendly interface for editing and deleting reviews.
