### ISSUE TITLE
USER STORY: Like / Unlike

### ISSUE THREAD

**Issue by Hugh1996** [Hugh1996/sabor-asturiano-pp4#7]
As a **Site User** I can **like or unlike a post** so that **can interact with the content**

## Acceptance Criteria
* Registered users can like or unlike a recipe post. 
* The like count updates in real-time.

## Tasks
- [x] Implement the frontend interface for liking/unliking.
- [x] Implement backend logic for handling like/unlike actions.
- [x] Update the like count in real-time.
